apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  labels:
    app.kubernetes.io/instance: basic-test
  name: k8s-playwright-app
  namespace: in-cluster
spec:
  generators:
    - git:
        files:
          - path: tork-cluster-config/**/playwright-config.json
        repoURL: 'https://github.com/johnnyrockoff/k8s-playwright-app.git'
        revision: master
  template:
    metadata:
      name: k8s-playwright-cronjob
    spec:
      destination:
        name: '{{cluster.name}}'
        namespace: in-cluster
      project: k8s-playwright-cronjob
      source:
        path: '/platform/playwright/basic/cronjob'
        repoURL: 'https://github.com/johnnyrockoff/k8s-playwright-cronjob.git'
        targetRevision: master
      syncPolicy:
        automated:
          prune: true
          selfHeal: true