apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: basic-automation-app
spec:
  generators:
    - git:
        repoURL: 'https://github.com/johnnyrockoff/k8s-playwright-app.git'
        revision: master
        files:
          - path: "tork-cluster-config/**/playwright-config.json"
  template:
    metadata:
      name: "{{ environment }}-basic-automation-app"
      annotations:
        notifications.argoproj.io/subscribe.on-health-degraded.teams: accelerationfrontendexperiencemojitoargo
        notifications.argoproj.io/subscribe.on-sync-failed.teams: accelerationfrontendexperiencemojitoargo
    spec:
      destination:
        namespace: basic-automation
        name: "{{cluster.name}}"
      project: basic-automation
      source:
        repoURL: 'https://github.com/johnnyrockoff/k8s-playwright-app.git'
        targetRevision: master
        path: "basic-automation-app-set/{{kustomize_path}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true