apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k8s-playwright
  namespace: badproxy
spec:
  generators:
    - git:
        repoURL: 'https://github.com/johnnyrockoff/k8s-playwright-app.git'
        revision: master
        files:
          - path: "cluster-config/dev/config.json"
  template:
    metadata:
      name: "test-automation-cronjob"
    spec:
      destination:
        namespace: badproxy
        server: https://kubernetes.default.svc
      project: k8s-playwright-app
      source:
        repoURL: 'https://github.com/johnnyrockoff/k8s-playwright-app.git'
        targetRevision: HEAD
        path: "automation-cronjob/"