# applicationset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tork-automation-app-set
spec:
  generators:
  - clusters:
      - name: in-cluster
        cluster: https://kubernetes.default.svc
    clusterDecision: cluster.ResourceCount
  template:
    metadata:
      labels:
        app: {{.Name}}
    spec:
      project: default
      source:
        repoURL: git@github.com:johnnyrockoff/k8s-playwright-app.git
        path: tork-cluster-config/**/playwright-config.json
        targetRevision: HEAD
      destination:
        server: https://kubernetes.default.svc
        namespace: {{.Name}}
      syncPolicy:
        automated:
          prune: true
