apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k8s-playwright-app
  namespace: in-cluster
spec:
  generators:
    - git:
        repoURL: "https://github.com/johnnyrockoff/k8s-playwright-app"
        revision: master
        files:
          - path: "tork-cluster-config/test/playwright-config.json"
  template:
    metadata:
      name: "{{name}}-app-set"
      namespace: default
    spec:
      destination:
        namespace: in-cluster
        server: https://kubernetes.default.svc
      project: default
      source:
        helm:
          parameters:
            - name: build.enabled
              value: "false"
            - name: deploy.route.enabled
              value: "false"
            - name: image.name
              value: k8s-playwright-cronjob-0.1.0
        chart: playwright-release
        repoURL: https://github.com/johnnyrockoff/k8s-playwright-cronjob
        targetRevision: 0.0.3
      syncPolicy:
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
          limit: 5
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true