apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k8s-playwright-app
  namespace: in-cluster
spec:
  generators:
    - git:
        repoURL: "https://github.com/johnnyrockoff/k8s-playwright-app"
        revision: master
        files:
          - path: "tork-cluster-config/test/playwright-config.json"
  template:
    metadata:
      name: "{{name}}-app-set"
      namespace: default
    spec:
      destination:
        namespace: in-cluster
        name: default
      project: k8s-playwright-cronjob
      source:
        repoURL: https://github.com/johnnyrockoff/k8s-playwright-cronjob
        chart: k8s-playwright-cronjob-0.1.0
        targetRevision: 1.0.0
        helm:
          parameters:
            - name: environment
              value: "{{values.environment}}"
            - name: squad
              value: "{{values.squad}}"
            - name: namespace
              value: "{{values.namespace}}"
            - name: defaults.cron_schedule
              value: "{{values.cron_schedule}}"
            - name: container_image
              value: "{{values.container_image}}"
            - name: defaults.user_assigned_identity_id
              value: "{{values.user_assigned_identity_id}}"
            - name: defaults.container_version
              value: "{{values.container_version}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true