apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k8s-playwright-app
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: "https://github.com/johnnyrockoff/k8s-playwright-app"
        revision: master
        files:
          - path: "tork-cluster-config/**/playwright-config.json"
          #- path: "cluster-config/**/tork-apitestrunner-config.json"
  template:
    metadata:
      name: "{{name}}-app-set"
      namespace: argocd
    spec:
      destination:
        namespace: kalimba
        name: "{{cluster.name}}"
      project: mojito-kalimba
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true