apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tork-automation-app
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: "git@github.com:johnnyrockoff/k8s-playwright-app.git"
        revision: master
        files:
          - path: "tork-cluster-config/**/playwright-config.json"
  template:
    metadata:
      name: "{{name}}-app-set"
      namespace: argocd
    spec:
      destination:
        namespace: basic
        name: "{{cluster.name}}"
      project: basic-test
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
