apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kalimba-automation-cronjob
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/johnnyrockoff/k8s-playwright-app'
        revision: master
        files:
          - path: "cluster-config/dev/config.json"
  template:
    metadata:
      name: "test-automation-cronjob"
    spec:
      destination:
        namespace: argocd
        name: in-cluster
      project: k8s-playwright-app
      source:
        repoURL: 'https://github.com/johnnyrockoff/k8s-playwright-app'
        targetRevision: master
        path: "automation-cronjob/"
      syncPolicy:
        automated:
          prune: true