apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  labels:
    app.kubernetes.io/instance: basic-test
  name: k8s-playwright-app
  namespace: in-cluster
spec:
  generators:
    - git:
        files:
          - path: tork-cluster-config/**/playwright-config.json
        repoURL: https://github.com/johnnyrockoff/k8s-playwright-app
        revision: HEAD
  template:
    metadata:
      name: k8s-playwright-cronjob
    spec:
      destination:
        server: https://kubernetes.default.svc
        namespace: in-cluster
      project: k8s-playwright-cronjob
      source:
        path: /tree/develop/platform/playwright/basic/cronjob/cronjob-test.yaml
        repoURL: https://github.com/johnnyrockoff/k8s-playwright-cronjob
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true