apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k8s-playwright-app
  namespace: default
spec:
  generators:
    - git:
        repoURL: "https://github.com/johnnyrockoff/k8s-playwright-app"
        revision: master
        files:
          - path: "tork-cluster-config/**/playwright-config.json"
  template:
    metadata:
      name: "{{name}}-app-set"
      namespace: default
    spec:
      destination:
        namespace: default
        name: kubernetes
      project: k8s-playwright-app
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true